spring:
  datasource:
    url: "${USER_DB_URL}"
    username: "${USER_DB_USERNAME}"
    password: "${USER_DB_PASSWORD}"

token:
  public-key: "${JWT_PUBLIC_KEY}"
  private-key: "${JWT_PRIVATE_KEY}"
  expiration: "${JWT_EXPIRATION}"
