spring:
  application:
    name: user-service

logbook:
  format:
    style: http
  obfuscate:
    headers:
      - Authorization
    json-body-fields:
      - password
      - accessToken
    replacement: <omitted>

logging:
  level:
    org:
      zalando:
        logbook: TRACE

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  tracing:
    sampling:
      probability: 1
  endpoint:
    health:
      show-components: always
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
    defaults:
      enabled: true