spring:
  application:
    name: task-service

logbook:
  format:
    style: http
  obfuscate:
    headers:
      - Authorization
    json-body-fields:
      - password
      - accessToken
    replacement: <omitted>

logging:
  level:
    org:
      zalando:
        logbook: TRACE